In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [87]:
df=pd.read_csv('/content/drive/My Drive/FatimaQurban_ML&DL_BytewiseFellowship2024/FatimaQurban_ML&DL_BWF_Task5/DATASET.csv')
df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA NAME,Crm Cd Desc,Vict Age,Vict Sex,Vict Descent,Weapon Desc,Status Desc,LOCATION
0,10304468,01/08/2020 0:00,01/08/2020 0:00,2230,Southwest,BATTERY - SIMPLE ASSAULT,36,F,B,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",Adult Other,1100 W 39TH PL
1,190101086,01/02/2020 0:00,01/01/2020 0:00,330,Central,BATTERY - SIMPLE ASSAULT,25,M,H,UNKNOWN WEAPON/OTHER WEAPON,Invest Cont,700 S HILL ST
2,200110444,04/14/2020 12:00:00 AM,02/13/2020 12:00:00 AM,1200,Central,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,0,X,X,NaN,Adult Arrest,200 E 6TH ST
3,191501505,01/01/2020 0:00,01/01/2020 0:00,1730,N Hollywood,VANDALISM - MISDEAMEANOR ($399 OR UNDER),76,F,W,NaN,Invest Cont,5400 CORTEEN PL
4,191921269,01/01/2020 0:00,01/01/2020 0:00,415,Mission,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",31,X,X,NaN,Invest Cont,14400 TITUS ST

### PART #1

In [37]:
df['TIME OCC']= df['TIME OCC'].astype(str) #  converting to string to to slice the column later
df['HOUR OCC']= df['TIME OCC'].str[:2].astype(int)
peak_crime_hour=df['HOUR OCC'].value_counts().idxmax()
print("Peak Crime Hour: ", peak_crime_hour)

Peak Crime Hour:  20

### PART #2

In [79]:
# peak_night_crime_location

df['TIME OCC']= df['TIME OCC'].astype(str)
df['HOUR OCC']=df['TIME OCC'].str[:2].astype(int)
# til_midnight= df['HOUR OCC']>22 && df['HOUR OCC']<24
crime_hours=(df['HOUR OCC']>22) | (df['HOUR OCC']<5)
peak_hours=df[crime_hours]
peak_night_crimes = peak_hours['AREA NAME'].value_counts()
print("peak night crimes and their location ", peak_night_crimes)

peak night crimes and their location  AREA NAME
Central        338
Southwest      291
Harbor         288
Rampart        238
Hollenbeck     227
Hollywood      149
Northeast      138
West LA        129
West Valley    129
Van Nuys       113
Wilshire        96
N Hollywood     69
Pacific         56
Olympic         42
Devonshire      41
77th Street     39
Newton          39
Mission         37
Southeast       34
Foothill        26
Topanga         23
Name: count, dtype: int64

In [81]:
peak_night_crime_location= peak_night_crimes.idxmax()
print("peak night crime location is ", peak_night_crime_location)

peak night crime location is  Central

### PART # 3

In [102]:
# Define bins and labels
bins = [0, 17, 25, 34, 44, 54, 64, float('inf')]
labels = ["0-17", "18-25", "26-34", "35-44", "45-54", "55-64", "65+"]

df['Age Category'] = pd.cut(df['Vict Age'], bins=bins, labels=labels)
print(df['Age Category'])

0       35-44
1       18-25
2         NaN
3         65+
4       26-34
        ...
9995      65+
9996      NaN
9997    35-44
9998    45-54
9999    55-64
Name: Vict Age, Length: 10000, dtype: category
Categories (7, object): ['0-17' < '18-25' < '26-34' < '35-44' < '45-54' < '55-64' < '65+']

In [105]:
age_crime_freq = df.groupby('Age Category').size()

# Create a pandas Series with age group labels as index and crime frequencies as values
victim_ages = pd.Series(age_crime_freq, index=labels)
print(victim_ages)

0-17      187
18-25    1232
26-34    2004
35-44    1730
45-54    1276
55-64    1043
65+       626
dtype: int64